name: hauptkanalmemory
description: A game around the inner citiy of Papenburg.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.7+20

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intl: "^0.16.1"

  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_fonts: ^0.2.0
  assets_audio_player: ^2.0.13
  json_annotation: ^3.1.1
  games_services: ^1.0.0
  flip_card: ^0.4.4
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/hauptkanalLinks/
    - assets/hauptkanalRechts/
    - assets/pbglion.png
    - assets/flick.wav
    - assets/swoosh.wav
    - assets/suck.wav
    - assets/bad.mp3
    - lang/de.json
    - lang/en.json
