name: hauptkanalmemory
description: A game around the inner city of Papenburg.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+38

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  google_fonts: ^6.1.0
  firebase_core: ^3.6.0
  games_services: ^4.0.0
  flip_card: ^0.7.0
  vibration: ^3.1.3
  wakelock_plus: ^1.1.4
  intl: any
  intl_utils: ^2.8.10
  audioplayers: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/left2018/
    - assets/right2018/
    - assets/left2022/
    - assets/right2022/
    - assets/pbglion.png
    - assets/pbgLocals.png
    - assets/background.jpg
    - assets/flick.wav
    - assets/swoosh.wav
    - assets/suck.wav
    - assets/bad.mp3
    - assets/515615__mrthenoronha__8-bit-game-theme.wav
    - assets/518305__mrthenoronha__stage-clear-8-bit.wav
    - assets/520937__mrthenoronha__8-bit-game-intro-loop.wav
    - assets/516824__mrthenoronha__get-item-4-8-bit.wav

flutter_intl:
  enabled: true
