// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaOHx7i6ZxKjeYNG6Icl_jDfZCSuZt87o',
    appId: '1:904963168550:android:4fa72abe20d98832',
    messagingSenderId: '904963168550',
    projectId: 'hauptkanal-memory-40871101',
    databaseURL: 'https://hauptkanal-memory-40871101.firebaseio.com',
    storageBucket: 'hauptkanal-memory-40871101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-MpMZCipYGTBgFQMbUkF1Gp2gLPHSIRw',
    appId: '1:904963168550:ios:7a90ff60defdd49cebc9e7',
    messagingSenderId: '904963168550',
    projectId: 'hauptkanal-memory-40871101',
    databaseURL: 'https://hauptkanal-memory-40871101.firebaseio.com',
    storageBucket: 'hauptkanal-memory-40871101.appspot.com',
    iosClientId: '904963168550-ml4fnu9j9fr1cfo2eh5cr4ltrsfkbqqa.apps.googleusercontent.com',
    iosBundleId: 'de.pasligh.ios.hauptkanalmemory',
  );
}
